CREATE DATABASE IF NOT EXISTS mexicangeek_db;

CREATE TABLE IF NOT EXISTS Products (
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
available BINARY NOT NULL,
price DECIMAL UNSIGNED NOT NULL,
cover VARCHAR(100),
description TEXT NOT NULL,
discount TINYINT UNSIGNED ,
type VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Comics(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
release_date DATE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Collectibles(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Editorials(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
cover VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Writers(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Users(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL,
password VARCHAR(50) NOT NULL,
age TINYINT UNSIGNED NOT NULL,
city VARCHAR(30) NOT NULL,
address VARCHAR(30) NOT NULL,
cp VARCHAR(15) NOT NULL,
avatar VARCHAR(100),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Purchases(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
total DECIMAL UNSIGNED NOT NULL,
date DATE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Countries(
id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE comics
ADD COLUMN editorial_id INT UNSIGNED,
ADD COLUMN writer_id INT UNSIGNED,
ADD COLUMN product_id INT UNSIGNED;

ALTER TABLE comics 
ADD CONSTRAINT fk_editorial_id FOREIGN KEY (editorial_id) REFERENCES editorials(id),
ADD CONSTRAINT fk_writer_id FOREIGN KEY (writer_id) REFERENCES writers(id),
ADD CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products(id);

ALTER TABLE collectibles
ADD COLUMN product_id INT UNSIGNED;

ALTER TABLE collectibles
ADD CONSTRAINT fk_collectibles_product_id FOREIGN KEY (product_id) REFERENCES products(id);

ALTER TABLE purchases
ADD COLUMN product_id INT UNSIGNED,
ADD COLUMN user_id INT UNSIGNED;

ALTER TABLE purchases
ADD CONSTRAINT fk_purchases_product_id FOREIGN KEY (product_id) REFERENCES products(id),
ADD CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES users(id);

ALTER TABLE users
ADD COLUMN country_id INT UNSIGNED;

ALTER TABLE users
ADD CONSTRAINT fk_users_country_id FOREIGN KEY (country_id) REFERENCES countries(id);


