insert into countries (id, name) values (1, 'México');
insert into countries (id, name) values (2, 'Colombia');
insert into countries (id, name) values (3, 'USA');
insert into countries (id, name) values (4, 'Venezuela');
insert into countries (id, name) values (5, 'Perú');
insert into countries (id, name) values (6, 'Cánada');
insert into countries (id, name) values (7, 'Honduras');
insert into countries (id, name) values (8, 'Guatemala');
insert into countries (id, name) values (9, 'El Salvador');
insert into countries (id, name) values (10, 'Chile');
insert into countries (id, name) values (11, 'Argentina');
insert into countries (id, name) values (12, 'Brazil');
